base_url = "https://bishwasaha.pages.dev"
compile_sass = true
build_search_index = false
theme = "anemone"

[markdown]
highlight_code = true
renger_emoji = true
external_links_target_blank = true

[extra]

[[extra.header_nav]]
en = { name = "/home/", url = "/" }

[[extra.header_nav]]
en = { name = "/projects/", url = "/projects" }
