base_url = "https://bishwasaha.com"
compile_sass = true
build_search_index = false
theme = "anemone"

[markdown]
highlight_code = true
renger_emoji = true
external_links_target_blank = true

[extra]
default_theme = "dark"

[[extra.header_nav]]
en = { name = "/home/", url = "/" }

[[extra.header_nav]]
en = { name = "/now/", url = "/now" }

[[extra.header_nav]]
en = { name = "/projects/", url = "/projects" }
