base_url = "https://bishwasaha.com"
compile_sass = true
build_search_index = false
theme = "anemone"

[markdown]
highlight_code = true
renger_emoji = true
external_links_target_blank = true

[extra]
default_theme = "dark"

header_nav = [
    { url = "/", name_en = "/home/" },
    { url = "/now", name_en = "/now/" },
    { url = "/projects", name_en = "/projects/" },
]
